module.exports = {
  CHANGE_SORT: 'CHANGE_SORT',
  LOAD_SETS: 'LOAD_SETS',
  SHUFFLE_CARDS: 'SHUFFLE_CARDS',
  START_QUIZ: 'START_QUIZ',
  QUIZ_CARD_CORRECT: 'QUIZ_CARD_CORRECT',
  QUIZ_CARD_INCORRECT: 'QUIZ_CARD_INCORRECT',
  SET_EDIT_NAME_CHANGE: 'SET_EDIT_NAME_CHANGE',
  SET_EDIT_DESCRIPTION_CHANGE: 'SET_EDIT_DESCRIPTION_CHANGE',
  QUIZ_CARD_SKIP: 'QUIZ_CARD_SKIP',
  DELETE_SINGLE_CARD: 'DELETE_SINGLE_CARD',
  EDIT_SET: 'EDIT_SET',
  SKIP_CARD: 'SKIP_CARD',
  CHANGE_INPUT: 'CHANGE_INPUT',
  ADD_EDIT_SET: 'ADD_EDIT_SET'
}
